/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/predictor': typeof PredictorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/predictor': typeof PredictorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/predictor': typeof PredictorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/neighborhoods'
    | '/predictor'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmarks' | '/neighborhoods' | '/predictor' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/neighborhoods'
    | '/predictor'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  NeighborhoodsRoute: typeof NeighborhoodsRoute
  PredictorRoute: typeof PredictorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  NeighborhoodsRoute: NeighborhoodsRoute,
  PredictorRoute: PredictorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
